import { useState } from "react";
import {
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  Divider,
  IconButton,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Paper,
  TextField,
  Typography,
} from "@mui/material";
import CloudUploadIcon from "@mui/icons-material/CloudUpload";
import DescriptionIcon from "@mui/icons-material/Description";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import AutoFixHighIcon from "@mui/icons-material/AutoFixHigh";
import SmartToyIcon from "@mui/icons-material/SmartToy";
import SendIcon from "@mui/icons-material/Send";
import StepperLayout from "../components/StepperLayout";

const requiredDocs = [
  { name: "Business Registration (Gewerbeanmeldung)", uploaded: false },
  { name: "Latest Annual Financial Statement", uploaded: false },
  { name: "Tax Certificate (Steuerbescheinigung)", uploaded: false },
  { name: "Project Cost Breakdown", uploaded: false },
];

const reviewSections = [
  {
    title: "Company Information",
    items: ["Company Name", "Address", "Size & Industry", "Revenue & Tax ID"],
  },
  {
    title: "Selected Funding",
    items: ["Program name", "Provider", "Maximum amount"],
  },
  {
    title: "Project Details",
    items: ["Title", "Summary", "Budget"],
  },
];

const aiPlanSteps = [
  "Verify company eligibility based on size and industry requirements",
  "Cross-reference project scope with Digital Jetzt program criteria",
  "Auto-generate the \"Digitalisierungsplan\" section from your project summary",
  "Calculate eligible cost items and maximum funding amount",
  "Pre-fill the official application PDF with all collected data",
  "Flag any missing information or documents before submission",
];

interface ChatMessage {
  role: "user" | "agent";
  text: string;
}

export default function DocumentsReview() {
  const [chatOpen, setChatOpen] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      role: "agent",
      text: "Hi! I'm your funding assistant. I've reviewed your application — everything looks good so far. Do you have any questions before submitting?",
    },
  ]);
  const [input, setInput] = useState("");

  const handleSend = () => {
    if (!input.trim()) return;
    const userMsg = input.trim();
    setMessages((prev) => [...prev, { role: "user", text: userMsg }]);
    setInput("");
    // TODO: Replace with real backend agent call
    setTimeout(() => {
      setMessages((prev) => [
        ...prev,
        {
          role: "agent",
          text: "Thanks for your question! Our team will look into this. For now, your application data looks complete and ready for submission.",
        },
      ]);
    }, 1500);
  };

  return (
    <StepperLayout>
      <Typography variant="h5" gutterBottom>
        Documents & Review
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
        Upload required documents, review the AI plan, and chat with our
        assistant if you need help.
      </Typography>

      {/* Upload Section */}
      <Typography variant="h6" sx={{ mb: 2 }}>
        Required Documents
      </Typography>
      <Card sx={{ mb: 4 }}>
        <CardContent>
          <List disablePadding>
            {requiredDocs.map((doc, i) => (
              <Box key={doc.name}>
                <ListItem
                  secondaryAction={
                    <Button
                      size="small"
                      variant="outlined"
                      startIcon={<CloudUploadIcon />}
                    >
                      Upload
                    </Button>
                  }
                >
                  <ListItemIcon>
                    <DescriptionIcon color="action" />
                  </ListItemIcon>
                  <ListItemText
                    primary={doc.name}
                    secondary={doc.uploaded ? "Uploaded" : "Not uploaded yet"}
                  />
                </ListItem>
                {i < requiredDocs.length - 1 && <Divider />}
              </Box>
            ))}
          </List>
        </CardContent>
      </Card>

      {/* AI Plan Overview */}
      <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 2 }}>
        <Typography variant="h6">AI Application Plan</Typography>
        <Chip
          icon={<AutoFixHighIcon />}
          label="Generated by AI"
          size="small"
          color="secondary"
          variant="outlined"
        />
      </Box>
      <Card sx={{ mb: 4, borderLeft: "4px solid", borderColor: "secondary.main" }}>
        <CardContent>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Here's what our AI will do to complete your application:
          </Typography>
          <List dense disablePadding>
            {aiPlanSteps.map((step, i) => (
              <ListItem key={i} disableGutters>
                <ListItemIcon sx={{ minWidth: 32 }}>
                  <Chip
                    label={i + 1}
                    size="small"
                    color="secondary"
                    sx={{
                      height: 22,
                      width: 22,
                      "& .MuiChip-label": { px: 0 },
                    }}
                  />
                </ListItemIcon>
                <ListItemText primary={step} />
              </ListItem>
            ))}
          </List>
        </CardContent>
      </Card>

      {/* Application Summary */}
      <Typography variant="h6" sx={{ mb: 2 }}>
        Application Summary
      </Typography>
      {reviewSections.map((section) => (
        <Card key={section.title} sx={{ mb: 2 }}>
          <CardContent>
            <Typography variant="subtitle1" fontWeight={600} gutterBottom>
              {section.title}
            </Typography>
            <List dense disablePadding>
              {section.items.map((item) => (
                <ListItem key={item} disableGutters>
                  <ListItemIcon sx={{ minWidth: 32 }}>
                    <CheckCircleIcon color="success" fontSize="small" />
                  </ListItemIcon>
                  <ListItemText primary={item} secondary="—" />
                </ListItem>
              ))}
            </List>
          </CardContent>
        </Card>
      ))}

      {/* Chat with Agent */}
      <Divider sx={{ my: 3 }} />
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          mb: 2,
        }}
      >
        <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
          <SmartToyIcon color="primary" />
          <Typography variant="h6">Need help? Chat with our AI assistant</Typography>
        </Box>
        {!chatOpen && (
          <Button
            variant="outlined"
            startIcon={<SmartToyIcon />}
            onClick={() => setChatOpen(true)}
          >
            Open Chat
          </Button>
        )}
      </Box>

      {chatOpen && (
        <Card variant="outlined" sx={{ borderColor: "primary.light" }}>
          <CardContent sx={{ p: 0 }}>
            <Box sx={{ maxHeight: 300, overflowY: "auto", p: 2 }}>
              {messages.map((msg, i) => (
                <Box
                  key={i}
                  sx={{
                    display: "flex",
                    justifyContent: msg.role === "user" ? "flex-end" : "flex-start",
                    mb: 1.5,
                  }}
                >
                  <Paper
                    elevation={0}
                    sx={{
                      px: 2,
                      py: 1,
                      maxWidth: "75%",
                      bgcolor: msg.role === "user" ? "primary.main" : "grey.100",
                      color: msg.role === "user" ? "white" : "text.primary",
                      borderRadius: 2,
                    }}
                  >
                    <Typography variant="body2">{msg.text}</Typography>
                  </Paper>
                </Box>
              ))}
            </Box>
            <Divider />
            <Box sx={{ display: "flex", gap: 1, p: 1.5 }}>
              <TextField
                size="small"
                placeholder="Ask a question about your application..."
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleSend()}
              />
              <IconButton color="primary" onClick={handleSend} disabled={!input.trim()}>
                <SendIcon />
              </IconButton>
            </Box>
          </CardContent>
        </Card>
      )}
    </StepperLayout>
  );
}
